server:
  port: 8081
    
spring:
  application:
    name: product-service

product:
  service:
    base-url: http://localhost:8081/api/products


spring:
  cloud:
    config:
      uri: http://localhost:8888
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


