spring:
  application:
    name: product-service  # must match the config file name in Git
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8081

spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
